from tkinter import N
from typing import Any, Callable, TypedDict, Optional
from weapon_skills_functions import *
from typing import Callable, TypedDict, Optional


class WeaponSkill(TypedDict, total=False):
    atk: tuple[str, Callable]


class Skills(TypedDict, total=False):
    omega: dict[str, Any]


class WeaponSkillElement(TypedDict, total=False):
    fire: Skills
    water: Skills
    earth: Skills
    wind: Skills
    light: Skills
    dark: Skills


test: dict[str, Optional[WeaponSkillElement]] = {
    "Mistfall's Might": {
        "dark": {"omega": {"atk": ("medium", get_omega_atk_up_percent_by_level)}}
    },
}

skill_mapping: dict[str, Optional[WeaponSkillElement]] = {
    "21 Excellent-Grade Sword": None,
    "A Pro's Tool": None,
    "A Thousand Dreams": None,
    "Abandoned Role": None,
    "Absolute Equality": None,
    "Abyssal Avenger": None,
    "Act of God": None,
    "Adjudicator's Doctrine": None,
    "Adjudicator's Revelation": None,
    "Adjudicator's Supremacy": None,
    "Air Blast": None,
    "Alchemic Regeneration": None,
    "All That Glitters Are Apples": None,
    "All-Night Party": None,
    "Almost Alchemy": None,
    "Amber Arts": None,
    "Amber Craft": None,
    "Amber Enforcement": None,
    "Amber Hunt": None,
    "Amber Resonator": None,
    "Amethyst's Grace": None,
    "Amethyst's Splendor": None,
    "Anointed Overture": None,
    "Anti-Cursed Spirit Weaponry": None,
    "Apex Predator": None,
    "Apocalyptic Power II": None,
    "Aquae Excelsior": None,
    "Arcanist's Essence": None,
    "Arcanist's Nature": None,
    "Architect ATK Ⅱ": None,
    "Architect Battle Arts": None,
    "Arcus Rubell": None,
    "Arma Rubell": None,
    "Armed Blaze": None,
    "Armed Flood": None,
    "Armed Gale": None,
    "Armed Grounds": None,
    "Armed Shadow": None,
    "Armed Shine": None,
    "Arrow Storm": None,
    "Arsus Excelsior": None,
    "Aspire to Shine!": None,
    "Astral Arts II": None,
    "Astral Blow II": None,
    "Astral Claw II": None,
    "Astral Echo II": None,
    "Astral Pierce II": None,
    "Astral Thrust II": None,
    "Audacity": None,
    "Aura Divine": None,
    "Authentic Memoirs": None,
    "Authority's Trium": None,
    "Auto Apparatus": None,
    "Axe Voltage II": None,
    "Axe's Wrath": None,
    "Azure Blade's Discipline": None,
    "Azure Bow's Discipline": None,
    "Azure Covenant": None,
    "Azure Dagger's Discipline": None,
    "Azure Gauntlet's Discipline": None,
    "Azure Harp's Discipline": None,
    "Azure Lance's Discipline": None,
    "Azure Rifle's Discipline": None,
    "Azure Rod's Discipline": None,
    "Azure Scythe's Discipline": None,
    "Azure Sword's Discipline": None,
    "Baculum Rubell": None,
    "Balmy Healing Breeze": None,
    "Bamboo's Might": None,
    "Bang!": None,
    "Banquet of Joy": None,
    "Barbarian's Essence": None,
    "Barbarian's Nature": None,
    "Battlefield Tribulations": None,
    "Bells of Grace": None,
    "Birch's Might": None,
    "Bitter Perseverance": None,
    "Black Covenant": None,
    "Black Night Fever": None,
    "Blade of Conquest": None,
    "Blade's Wrath": None,
    "Blaze's Ascendancy": None,
    "Blaze's Crux": None,
    "Blaze's Exertion": None,
    "Blaze's Initiation": None,
    "Blaze's Pact": None,
    "Blaze's Persistence": None,
    "Blaze's Quintessence": None,
    "Blazing Chain": None,
    "Blood Drip": None,
    "Blood Red Blow": None,
    "Blood Rose Barrier": None,
    "Blood Rose Brier": None,
    "Blood Rose Bud": None,
    "Blood Rose Thorns": None,
    "Bloodsip Flash": None,
    "Bloodthirsty Deities": None,
    "Blossom's Might": None,
    "Bountiful Guidance": None,
    "Bountiful Influence": None,
    "Bountiful Protection": None,
    "Bountiful Strike": None,
    "Bow Voltage": None,
    "Bow Voltage II": None,
    "Breath of Mysteria": None,
    "Bronze Rose Barrier": None,
    "Bronze Rose Brier": None,
    "Bronze Rose Bud": None,
    "Bronze Rose Thorns": None,
    "Calamitous Covenant": None,
    "Caliginis Excelsior": None,
    "Carrot Hamburger": None,
    "Cavalier's Apex": None,
    "Cavalier's Nature": None,
    "Ceaseless Striving": None,
    "Celestial Guidance": None,
    "Cepheid Variable": None,
    "Chain Force": None,
    "Chariot-Star's Wish": None,
    "Cheirokmeta": None,
    "Choking": None,
    "Chthonian Bewailer's Sanctity": None,
    "Class-Trip Memories": None,
    "Clawed Flood": None,
    "Climate Control": None,
    "Clouds of Nightfall": None,
    "Cobalt Arts": None,
    "Cobalt Craft": None,
    "Cobalt Enforcement": None,
    "Cobalt Hunt": None,
    "Cobalt Vitality": None,
    "Coeli Excelsior": None,
    "Concrio Albus": None,
    "Concrio Corun": None,
    "Concrio Ignis": None,
    "Concrio Imber": None,
    "Concrio Khelreos": None,
    "Concrio Rubell": None,
    "Concrio Terra": None,
    "Concrio Ventus": None,
    "Consecrated Sacrifice": None,
    "Contentious Covenant": None,
    "Contractor's Apex": None,
    "Contractor's Nature": None,
    "Conviction Arc": None,
    "Conviction's Double Star": None,
    "Cosmic Blade II": None,
    "Cosmic Bow II": None,
    "Cosmic Dagger II": None,
    "Cosmic Gauntlet II": None,
    "Cosmic Harp II": None,
    "Cosmic Lance II": None,
    "Cosmic Rifle II": None,
    "Cosmic Rod II": None,
    "Cosmic Scythe II": None,
    "Cosmic Sword II": None,
    "Covert Artistry": None,
    "Crimsonic Liege": None,
    "Crustacean's Might": None,
    "Crustaceous Crush": None,
    "Culmination of Nightfall": None,
    "Cursed Halberd": None,
    "Cursed Tentacle": None,
    "Cyclonic Strike": None,
    "Dagger Voltage II": None,
    "Dancer's Discipline": None,
    "Dancer's Essence": None,
    "Dancer's Nature": None,
    "Dark Demon-Edge": None,
    "Dark Destructo Fist": None,
    "Dark Drain": None,
    "Dark's Aegis": None,
    "Dark's Celere": None,
    "Dark's Dual-Edge": None,
    "Dark's Enmity": None,
    "Dark's Fandango": None,
    "Dark's Grace": None,
    "Dark's Majesty": None,
    "Dark's Might": None,
    "Dark's Restraint": None,
    "Dark's Sentence": None,
    "Dark's Trium": None,
    "Dark's Verity": None,
    "Darkness Concealer": None,
    "Deathly Pincers": None,
    "Debauchery's Sway II": None,
    "Debauchery's Sway III": None,
    "Deleterious Covenant": None,
    "Delicate Strings": None,
    "Delinquent Heart": None,
    "Desert Yellow Blow": None,
    "Despair's Quickening": None,
    "Devicer": None,
    "Dexterity": None,
    "Disease Demon": None,
    "Divine Gavel": None,
    "Do Not Lose or Else": None,
    "Doc Agasa's Invention": None,
    "Doctor's Essence": None,
    "Doctor's Nature": None,
    "Downfall of Ignorance": None,
    "Dragon Ravager's Might": None,
    "Dragonstrike's Pursuit": None,
    "Dragonstrike's Wisdom": None,
    "Dragoon's Apex": None,
    "Dragoon's Nature": None,
    "Draph Animus Dominion": None,
    "Draph Animus Parity": None,
    "Draph Animus Utopia": None,
    "Dreadflame's Claws": None,
    "Dreadflame's Supremacy": None,
    "Dreamward Gate": None,
    "Drive Sprocket": None,
    "Drum Master's Battery": None,
    "Dual Blade's Essence": None,
    "Dual Blade's Nature": None,
    "Eagle and Human's Prudence": None,
    "Earth's Aegis": None,
    "Earth's Bladeshield": None,
    "Earth's Celere": None,
    "Earth's Dual-Edge": None,
    "Earth's Enmity": None,
    "Earth's Fandango": None,
    "Earth's Garrison": None,
    "Earth's Healing": None,
    "Earth's Majesty": None,
    "Earth's Might": None,
    "Earth's Mystery": None,
    "Earth's Sentence": None,
    "Earth's Stamina": None,
    "Earth's Verity": None,
    "Ebony Blade": None,
    "Echinoderm": None,
    "Eclipse's Stamina": None,
    "Einar": None,
    "Electrifying Onslaught": None,
    "Elegant Stratagem": None,
    "Elysian Windrider's Sanctity": None,
    "Emerald Covenant": None,
    "Emerald Rose Barrier": None,
    "Emerald Rose Brier": None,
    "Emerald Rose Bud": None,
    "Emerald Rose Thorns": None,
    "Emperor-Judgement's Awakening": None,
    "Empress-Justice's Virtue": None,
    "Empyrean Adjudicator's Sanctity": None,
    "Enchantress's Barrier": None,
    "Enlightened Monk's Apex": None,
    "Enlightened Monk's Nature": None,
    "Enriching Elevation": None,
    "Erune Animus Dominion": None,
    "Erune Animus Parity": None,
    "Erune Animus Utopia": None,
    "Essence of the East": None,
    "Essence of the North": None,
    "Essence of the South": None,
    "Essence of the West": None,
    "Eternal Animosity": None,
    "Ever-Watching Eye": None,
    "Evergreen Sovereign": None,
    "Ewiyar's Gale": None,
    "Exceed": None,
    "Excess Voltage": None,
    "Executioner's Essence": None,
    "Executioner's Nature": None,
    "Fang of the Way": None,
    "Fediel's Eclipse": None,
    "Femme Fatale": None,
    "Feral Roar": None,
    "Fine Wind, Clear Heart": None,
    "Fire Barrier": None,
    "Fire's Aegis": None,
    "Fire's Bladeshield": None,
    "Fire's Celere": None,
    "Fire's Clarity": None,
    "Fire's Dual-Edge": None,
    "Fire's Enmity": None,
    "Fire's Fandango": None,
    "Fire's Garrison": None,
    "Fire's Healing": None,
    "Fire's Majesty": None,
    "Fire's Might": None,
    "Fire's Mystery": None,
    "Fire's Sentence": None,
    "Fire's Stamina": None,
    "Fire's Trium": None,
    "Fire's Verity": None,
    "Firestorm's Enmity": None,
    "Flames of Prosperity": None,
    "Fleeting Wisps": None,
    "Flesh Ripper": None,
    "Flood's Verity": None,
    "Fluffy-Wuffy Tail": None,
    "Fluttering Slash": None,
    "Focus Attack": None,
    "Fool-Hanged Man's Perseverance": None,
    "Forbidden Putrefaction": None,
    "Forbidden Training": None,
    "Forest Blessing": None,
    "Forest Dweller's Insight": None,
    "Fortified Blade": None,
    "Fortified Gauntlet": None,
    "Fortified Harp": None,
    "Fortified Staff": None,
    "Fortuitous Wind Covenant": None,
    "Four Orbs' Judgment": None,
    "Foxflame's Flicker": None,
    "Foxflame's Glare": None,
    "Foxy Seclusion": None,
    "Freedom's Way": None,
    "Fresh Catch's Might": None,
    "Frozen Blade": None,
    "Gabriel's Blessing II": None,
    "Gabriel's Blessing III": None,
    "Gachapin's Might": None,
    "Galactic Bulge": None,
    "Gale Green Blow": None,
    "Gale's Might": None,
    "Galleon's Landslide": None,
    "Game Changer": None,
    "Gate of Omnipotence": None,
    "Gate of Wisdom": None,
    "Gauntlet Voltage II": None,
    "Gauntlet's Wrath": None,
    "Geisa Ari": None,
    "Ghost on the Battlefield": None,
    "Gilded in Sage": None,
    "Glacial Flight": None,
    "Glacial Frostcage": None,
    "Glacial Supremacy": None,
    "Gladius Rubell": None,
    "Glimmer's Ascendancy": None,
    "Glimmer's Crux": None,
    "Glimmer's Fortitude": None,
    "Glimmer's Pact": None,
    "Glimmer's Persistence": None,
    "Glimmer's Quenching": None,
    "Glimmer's Quintessence": None,
    "God of Death": None,
    "Gold Covenant": None,
    "Gold's Gleam": None,
    "Golden Advent II": None,
    "Golden Arts": None,
    "Golden Craft": None,
    "Golden Enforcement": None,
    "Golden Hunt": None,
    "Golden Night Fever": None,
    "Golden Spirit": None,
    "Golden Vitality": None,
    "Goldslime's Aegis": None,
    "Good and Tasty": None,
    "Gourmet Banana": None,
    "Grace of Healing II": None,
    "Grace of the Omnilight": None,
    "Grand Epic": None,
    "Grand Works": None,
    "Graphite Arts": None,
    "Graphite Convergence": None,
    "Graphite Craft": None,
    "Graphite Enforcement": None,
    "Graphite Hunt": None,
    "Great Sword Under Heaven": None,
    "Great Turbine": None,
    "Greatsnake's Lord-Sword": None,
    "Gugalanna": None,
    "Guiding Gospel": None,
    "Guiding Revelation": None,
    "Gun Voltage II": None,
    "Gunslinger's Essence": None,
    "Gunslinger's Nature": None,
    "Harbinger of Destruction": None,
    "Harbinger of the Dark Sunrise": None,
    "Harbinger of the Dusk of Nightfall": None,
    "Harp Voltage II": None,
    "Harp of Hastened Light": None,
    "Harvin Animus Dominion": None,
    "Harvin Animus Parity": None,
    "Harvin Animus Utopia": None,
    "Hatred's Celere": None,
    "Hatred's Clarity": None,
    "Hatred's Dual-Edge": None,
    "Hatred's Enmity": None,
    "Hatred's Fandango": None,
    "Hatred's Garrison": None,
    "Hatred's Grace": None,
    "Hatred's Haunt": None,
    "Hatred's Healing": None,
    "Hatred's Majesty": None,
    "Hatred's Might": None,
    "Hatred's Mystery": None,
    "Hatred's Primacy": None,
    "Hatred's Progression": None,
    "Hatred's Restraint": None,
    "Hatred's Stamina": None,
    "Hatred's Trium": None,
    "Hatred's Verity": None,
    "Heated Spearswipe": None,
    "Heaven's Truth": None,
    "Heliacal Sovereign": None,
    "Hellfire's Aegis": None,
    "Hellfire's Celere": None,
    "Hellfire's Clarity": None,
    "Hellfire's Dual-Edge": None,
    "Hellfire's Enmity": None,
    "Hellfire's Essence": None,
    "Hellfire's Fandango": None,
    "Hellfire's Garrison": None,
    "Hellfire's Healing": None,
    "Hellfire's Majesty": None,
    "Hellfire's Might": None,
    "Hellfire's Primacy": None,
    "Hellfire's Progression": None,
    "Hellfire's Restraint": None,
    "Hellfire's Stamina": None,
    "Hellfire's Tempering": None,
    "Hellfire's Trium": None,
    "Hellfire's Verity": None,
    "Henny Holidays": None,
    "Herald of the Seraph": None,
    "Hermit-Temperance's Accord": None,
    "Hero's Stature": None,
    "Hero's Testament": None,
    "Heroic Tale": None,
    "Hidden Aim": None,
    "Hierophant-Sun's Blessing": None,
    "High Priestess-Moon's Bewitching": None,
    "Hoarfrost's Aegis": None,
    "Hoarfrost's Aegis II": None,
    "Hoarfrost's Bloodshed": None,
    "Hoarfrost's Celere": None,
    "Hoarfrost's Clarity": None,
    "Hoarfrost's Dual-Edge": None,
    "Hoarfrost's Enmity": None,
    "Hoarfrost's Fourth Pursuit": None,
    "Hoarfrost's Garrison": None,
    "Hoarfrost's Glory": None,
    "Hoarfrost's Healing": None,
    "Hoarfrost's Heed": None,
    "Hoarfrost's Majesty": None,
    "Hoarfrost's Might": None,
    "Hoarfrost's Might II": None,
    "Hoarfrost's Might III": None,
    "Hoarfrost's Mystery": None,
    "Hoarfrost's Progression": None,
    "Hoarfrost's Stamina": None,
    "Hoarfrost's Stamina II": None,
    "Hoarfrost's Tempering": None,
    "Hoarfrost's Tyranny": None,
    "Hoarfrost's Verity": None,
    "Holy Knight's Honor": None,
    "Horseman's Supremacy": None,
    "Hot Blood's Might": None,
    "Human Animus Dominion": None,
    "Human Animus Parity": None,
    "Human Animus Utopia": None,
    "Hundred Fists": None,
    "Hunger for Chaos": None,
    "Hydor Theion": None,
    "I'll Never Go Down": None,
    "Ice Cage Aura": None,
    "Ice Rose Barrier": None,
    "Ice Rose Brier": None,
    "Ice Rose Bud": None,
    "Ice Rose Thorns": None,
    "Ice Sprite Magic": None,
    "If You're Smiling, Any Day Is Okay!": None,
    "Immortal Dragonblood": None,
    "Impavid Impetus": None,
    "Impervious Covenant": None,
    "Incantation Fang": None,
    "Incursio Albus": None,
    "Incursio Corun": None,
    "Incursio Terra": None,
    "Incursio Ventus": None,
    "Indestructible Bachi": None,
    "Indomitable Loyalty": None,
    "Infernal's Rage": None,
    "Inferno's Aegis": None,
    "Inferno's Bloodshed": None,
    "Inferno's Celere II": None,
    "Inferno's Crux": None,
    "Inferno's Dual-Edge": None,
    "Inferno's Enmity": None,
    "Inferno's Garrison": None,
    "Inferno's Glory": None,
    "Inferno's Heed": None,
    "Inferno's Insignia": None,
    "Inferno's Majesty": None,
    "Inferno's Might": None,
    "Inferno's Might II": None,
    "Inferno's Might III": None,
    "Inferno's Mystery": None,
    "Inferno's Progression": None,
    "Inferno's Second Insignia": None,
    "Inferno's Sentence": None,
    "Inferno's Stamina": None,
    "Inferno's Tempering": None,
    "Inferno's Trium": None,
    "Inferno's Tyranny": None,
    "Inferno's Verity": None,
    "Insight of Elation": None,
    "Instinctive Forecast": None,
    "Intelligence": None,
    "Ironflame's Aegis": None,
    "Ironflame's Aegis II": None,
    "Ironflame's Celere II": None,
    "Ironflame's Clarity": None,
    "Ironflame's Clarity II": None,
    "Ironflame's Devastation": None,
    "Ironflame's Enmity": None,
    "Ironflame's Enmity III": None,
    "Ironflame's Gauntlet": None,
    "Ironflame's Majesty III": None,
    "Ironflame's Might": None,
    "Ironflame's Might II": None,
    "Ironflame's Primacy": None,
    "Ironflame's Progression II": None,
    "Ironflame's Sentence": None,
    "Ironflame's Stamina II": None,
    "It Follows": None,
    "Jade Arts": None,
    "Jade Craft": None,
    "Jade Enforcement": None,
    "Jade Hunt": None,
    "Jade Valuables": None,
    "Kengo's Essence": None,
    "Kengo's Nature": None,
    "Kind Woodcutter's Apex": None,
    "Kind Woodcutter's Nature": None,
    "Kingpin's Essence": None,
    "Kingpin's Nature": None,
    "Knightcode's Aegis": None,
    "Knightcode's Aegis II": None,
    "Knightcode's Celere": None,
    "Knightcode's Clarity": None,
    "Knightcode's Enmity": None,
    "Knightcode's Majesty": None,
    "Knightcode's Majesty III": None,
    "Knightcode's Might II": None,
    "Knightcode's Resolve": None,
    "Knightcode's Stamina": None,
    "Knightcode's Trituration": None,
    "Knightcode's Verity II": None,
    "Kuninaga Gojo Crafted": None,
    "Labrys Rubell": None,
    "Lancea Rubell": None,
    "Landslide's Mystery": None,
    "Layman's Saw of Death": None,
    "Legionnaire's Essence": None,
    "Legionnaire's Nature": None,
    "Let's Play": None,
    "Lifetree's Aegis": None,
    "Lifetree's Aegis II": None,
    "Lifetree's Enmity": None,
    "Lifetree's Enmity III": None,
    "Lifetree's Haunt": None,
    "Lifetree's Insignia III": None,
    "Lifetree's Majesty": None,
    "Lifetree's Majesty III": None,
    "Lifetree's Might": None,
    "Lifetree's Might II": None,
    "Lifetree's Progression II": None,
    "Lifetree's Restraint": None,
    "Lifetree's Stamina": None,
    "Lifetree's Trium III": None,
    "Lifetree's Truce": None,
    "Lifetree's Verity II": None,
    "Light's  Aegis": None,
    "Light's  Dual-Edge": None,
    "Light's  Enmity": None,
    "Light's Aegis": None,
    "Light's Celere": None,
    "Light's Enmity": None,
    "Light's Fandango": None,
    "Light's Garrison": None,
    "Light's Grace": None,
    "Light's Majesty": None,
    "Light's Might": None,
    "Light's Mystery": None,
    "Light's Refuge": None,
    "Light's Sentence": None,
    "Light's Stamina": None,
    "Light's Tempering": None,
    "Light's Trium": None,
    "Light's Verity": None,
    "Lightbeam's Might": None,
    "Lion and Cow's Call": None,
    "Locked on the Heart": None,
    "Loki's Wit": None,
    "Lone Wolf's Karma": None,
    "Longstrider's Apex": None,
    "Longstrider's Nature": None,
    "Lost Song of the Sages": None,
    "Love Forbidden": None,
    "Lovers-Death's Demise": None,
    "Loyalty's Flame": None,
    "Lu Woh's Authority": None,
    "Luctor Rubell": None,
    "Luminis Excelsior": None,
    "Lunatic Effect": None,
    "Mad Alveolar": None,
    "Magic Charge": None,
    "Magician-Tower's Calamity": None,
    "Make Our Dreams Come True": None,
    "Makhaira Rubell": None,
    "Making a Killing": None,
    "Mano a Mano": None,
    "Master of the Arcane": None,
    "Member of the Corps": None,
    "Memories of War": None,
    "Michael's Blessing II": None,
    "Michael's Blessing III": None,
    "Mifune Style, Binary Star": None,
    "Mifune Style, Zen Impact": None,
    "Mikill Las": None,
    "Mistfall's Aegis": None,
    "Mistfall's Aegis II": None,
    "Mistfall's Bloodshed III": None,
    "Mistfall's Enmity": None,
    "Mistfall's Heed": None,
    "Mistfall's Majesty II": None,
    "Mistfall's Majesty III": None,
    "Mistfall's Might": None,
    "Mistfall's Might II": None,
    "Mistfall's Restraint": None,
    "Mistfall's Sentence": None,
    "Mistfall's Stamina II": None,
    "Mistfall's Trituration": None,
    "Mistfall's Trium III": None,
    "Mistfall's Tyranny": None,
    "Mountain's Aegis": None,
    "Mountain's Celere": None,
    "Mountain's Clarity": None,
    "Mountain's Dual-Edge": None,
    "Mountain's Fandango": None,
    "Mountain's Garrison": None,
    "Mountain's Grace": None,
    "Mountain's Haunt": None,
    "Mountain's Healing": None,
    "Mountain's Majesty": None,
    "Mountain's Might": None,
    "Mountain's Primacy": None,
    "Mountain's Restraint": None,
    "Mountain's Sentence": None,
    "Mountain's Stamina": None,
    "Mountain's Trium": None,
    "Mountain's Verity": None,
    "Munechika Sanjo Crafted": None,
    "Musica Rubell": None,
    "Mutinous Flare": None,
    "Mutiny's Frost Blade": None,
    "Mutiny's Light Blade": None,
    "Mutiny's Shadow Blade": None,
    "Mutiny's Terra Blade": None,
    "My Words for You": None,
    "Mysteries of Mysteria": None,
    "Mysterious ATK": None,
    "Mysterious ATK II": None,
    "Mysterious VIT": None,
    "Mysterious VIT II": None,
    "Natural Satellite's Might": None,
    "Nature's Protection": None,
    "Nature's Providence": None,
    "Nature's Truth": None,
    "Nightbender's Essence": None,
    "Nightbender's Nature": None,
    "Noble's Dance": None,
    "Noble's Defense": None,
    "Nostalgic Summer": None,
    "Nue's Cry": None,
    "Nue's Omen": None,
    "Oblivion's Aegis": None,
    "Oblivion's Bloodshed": None,
    "Oblivion's Enmity": None,
    "Oblivion's Garrison": None,
    "Oblivion's Glory": None,
    "Oblivion's Healing": None,
    "Oblivion's Heed": None,
    "Oblivion's Majesty": None,
    "Oblivion's Might": None,
    "Oblivion's Might II": None,
    "Oblivion's Might III": None,
    "Oblivion's Mystery": None,
    "Oblivion's Progression": None,
    "Oblivion's Stamina": None,
    "Oblivion's Tempering": None,
    "Oblivion's Trium": None,
    "Oblivion's Tyranny": None,
    "Oblivion's Tyranny II": None,
    "Oblivion's Verity": None,
    "Oblivion's Verity II": None,
    "Ocean Blue Blow": None,
    "Oceansoul's Aegis II": None,
    "Oceansoul's Celere": None,
    "Oceansoul's Celere II": None,
    "Oceansoul's Enmity": None,
    "Oceansoul's Enmity II": None,
    "Oceansoul's Fandango": None,
    "Oceansoul's Healing II": None,
    "Oceansoul's Majesty": None,
    "Oceansoul's Majesty III": None,
    "Oceansoul's Might": None,
    "Oceansoul's Might II": None,
    "Oceansoul's Progression II": None,
    "Oceansoul's Restraint": None,
    "Oceansoul's Sentence": None,
    "Oceansoul's Sweep": None,
    "Oceansoul's Verity II": None,
    "Ogre's Retribution": None,
    "Old-School Style": None,
    "One Light": None,
    "One Star-Soaring Show": None,
    "One Sting, One Kill II": None,
    "One-Hit Hologram": None,
    "Opener's Might": None,
    "Ophidian Servitor": None,
    "Optimus Exalto Aeros": None,
    "Oracle's Allegiance": None,
    "Oracle's Boon": None,
    "Organic Smackdown": None,
    "Overdraw": None,
    "Paragon's Essence": None,
    "Paragon's Nature": None,
    "Paramita's Might": None,
    "Party's Peak": None,
    "Perforating Stake": None,
    "Phantasmagoric Fencer": None,
    "Phantom's Supremacy": None,
    "Pickup's Might": None,
    "Piercing Fang": None,
    "Playboy Destroyer": None,
    "Point and Shoot": None,
    "Possessive Passion": None,
    "Power Conduit": None,
    "Power of the Prism Stones": None,
    "Powerbomb": None,
    "Practice and Perfection": None,
    "Prayer of the Sunrise": None,
    "Preemptive Amber Barrier": None,
    "Preemptive Azure Barrier": None,
    "Preemptive Cloud Wall": None,
    "Preemptive Fire Blade": None,
    "Preemptive Fire Wall": None,
    "Preemptive Frost Blade": None,
    "Preemptive Gale Blade": None,
    "Preemptive Ice Wall": None,
    "Preemptive Light Blade": None,
    "Preemptive Rock Wall": None,
    "Preemptive Shadow Barrier": None,
    "Preemptive Shadow Blade": None,
    "Preemptive Silver Barrier": None,
    "Preemptive Silver Wall": None,
    "Preemptive Terra Blade": None,
    "Primal Pugilism": None,
    "Promenade of the Priestess": None,
    "Protector of Verona": None,
    "Proteus's Prophecy": None,
    "Psycho's Might": None,
    "Purgatory's Ascendancy": None,
    "Purgatory's Exertion": None,
    "Purgatory's Fortitude": None,
    "Purgatory's Initiation": None,
    "Purgatory's Marvel": None,
    "Purgatory's Pact": None,
    "Purgatory's Persistence": None,
    "Purgatory's Quintessence": None,
    "Purgatory's Spectacle": None,
    "Purity of Nature": None,
    "Rachis of Fire": None,
    "Radiant Pearl Blow": None,
    "Radiant Sovereign": None,
    "Rainbow-Colored Light": None,
    "Ranger Smoke": None,
    "Raphael's Blessing II": None,
    "Raphael's Blessing III": None,
    "Rapidus Draph Animus": None,
    "Rapidus Erune Animus": None,
    "Rapidus Harvin Animus": None,
    "Rapidus Human Animus": None,
    "Realm Binder": None,
    "Reigning Champ's Essence": None,
    "Reigning Champ's Nature": None,
    "Reincarnation": None,
    "Rending's Might": None,
    "Renew Soul": None,
    "Reptile Slaughter": None,
    "Resilient Gale": None,
    "Resilient Shadow": None,
    "Resort's Might": None,
    "Reverberating Rhythm": None,
    "Ridge's Fortitude": None,
    "Ridge's Persistence": None,
    "Ridge's Surge": None,
    "Riff on Resonance": None,
    "Rightway Pathfinder II": None,
    "Rindo Emblem": None,
    "Robar Tiempo": None,
    "Rockslide Bullet": None,
    "Rose's Refuge": None,
    "Rouge Pierre Tempest": None,
    "Royal Affection": None,
    "Royal Gift": None,
    "Royal Purple Blow": None,
    "Royal Wing Barrier": None,
    "Rugged Woodcutter's Apex": None,
    "Rugged Woodcutter's Nature": None,
    "Safeguard": None,
    "Sage's Aura": None,
    "Saint's Essence": None,
    "Saint's Nature": None,
    "Sangre Caliente": None,
    "Sauna-Goer's Companion": None,
    "Savage Mythology": None,
    "Saving Grace II": None,
    "Scales of Nightfall": None,
    "Scales of Wrath": None,
    "Scales of the Sunrise": None,
    "Scarlet Arts": None,
    "Scarlet Convergence": None,
    "Scarlet Craft": None,
    "Scarlet Enforcement": None,
    "Scarlet Hunt": None,
    "Scarlet Reticle": None,
    "School Idol": None,
    "Schoolmates": None,
    "Search for Enlightenment": None,
    "Searing Enlightener's Sanctity": None,
    "Self-taught Mastery": None,
    "Self-taught Swordsmanship": None,
    "Sentient Simulacrum": None,
    "Sephira Dark-Tek": None,
    "Sephira Earth-Tek": None,
    "Sephira Earthsoul": None,
    "Sephira Fire-Tek": None,
    "Sephira Firesoul": None,
    "Sephira Light-Tek": None,
    "Sephira Maxi-Dark": None,
    "Sephira Maxi-Earth": None,
    "Sephira Maxi-Fire": None,
    "Sephira Maxi-Light": None,
    "Sephira Maxi-Water": None,
    "Sephira Maxi-Wind": None,
    "Sephira Water-Tek": None,
    "Sephira Watersoul": None,
    "Sephira Wind-Tek": None,
    "Sephira Windsoul": None,
    "Sephirath Brogue": None,
    "Sephirath Corant": None,
    "Sephirath Eparc": None,
    "Sephirath Fusame": None,
    "Sephirath Haton": None,
    "Serenity's Mead": None,
    "Seven Gem Barrier": None,
    "Shadowhound's Essence": None,
    "Shadowhound's Nature": None,
    "Shadowverse Player": None,
    "Shady Business II": None,
    "Shall We Duel?": None,
    "Shark Attack!": None,
    "Shark Control": None,
    "Shell of the Bereft": None,
    "Shell-Piercing": None,
    "Shield-Tearing Dance": None,
    "Shining Beacon": None,
    "Shock on Contact": None,
    "Shoots and Leaves": None,
    "Shredder's Essence": None,
    "Shredder's Nature": None,
    "Sica Rubell": None,
    "Sidearm": None,
    "Sign from Above": None,
    "Silver's Sparkle": None,
    "Silverslime's Aegis": None,
    "Six Dragons' Radiance": None,
    "Six Pillars' Judgment": None,
    "Skyrule Storm": None,
    "Slaughterous Sovereign": None,
    "Slayer of Immortals II": None,
    "Slaysnake's Myth II": None,
    "Smiling Is Magic": None,
    "Snowfall's Ascendancy": None,
    "Snowfall's Crux": None,
    "Snowfall's Exertion": None,
    "Snowfall's Fortitude": None,
    "Snowfall's Marvel": None,
    "Snowfall's Pact": None,
    "Snowfall's Quenching": None,
    "Snowfall's Quintessence": None,
    "Solaris's Supremacy": None,
    "Soul Resonance": None,
    "Soulless Passage": None,
    "Sovereign Defender's Might": None,
    "Spear Voltage II": None,
    "Speed Cast": None,
    "Spirit Serenity": None,
    "Spirit of Giving": None,
    "Spirit of the Morning Star": None,
    "Spirit's Aegis": None,
    "Spirit's Might": None,
    "Splitting Bamboo": None,
    "Squad Goals": None,
    "Staff Resonance": None,
    "Staff Voltage II": None,
    "Sting of the Dragon Fang": None,
    "Stormwyrm's Abandon": None,
    "Stormwyrm's Aegis II": None,
    "Stormwyrm's Betrayal": None,
    "Stormwyrm's Enmity": None,
    "Stormwyrm's Essence": None,
    "Stormwyrm's Heroism II": None,
    "Stormwyrm's Majesty": None,
    "Stormwyrm's Majesty III": None,
    "Stormwyrm's Might": None,
    "Stormwyrm's Might II": None,
    "Stormwyrm's Progression II": None,
    "Stormwyrm's Restraint": None,
    "Stormwyrm's Stamina": None,
    "Stormwyrm's Tyranny": None,
    "Stormwyrm's Verity II": None,
    "Strategist's Temperament": None,
    "Street Fighter": None,
    "Strength": None,
    "Strength to Spare": None,
    "Strength-Devil's Seduction": None,
    "Striking Art": None,
    "Succession of Knighthood": None,
    "Sunlight's Stimulant": None,
    "Sunshiner": None,
    "Sunveil's Crown": None,
    "Sunveil's Radiance": None,
    "Suono Forte": None,
    "Super Abomideath Power Z": None,
    "Supremacy's Fist": None,
    "Supreme Trepidation": None,
    "Swiftblade Oath": None,
    "Sword Princess": None,
    "Sword Voltage": None,
    "Sword Voltage II": None,
    "Sword of the Saviour": None,
    "Sword's Charge": None,
    "Sword's Wrath": None,
    "Swordmaster's Soul": None,
    "Synchronized Artistry": None,
    "Teachers' Guidance II": None,
    "Teachers' Guidance III": None,
    "Technical Artistry": None,
    "Tell Ibrahim": None,
    "Tempest's Vestige": None,
    "Tenacious Dinosaur": None,
    "Terra's Aegis": None,
    "Terra's Aegis II": None,
    "Terra's Bloodshed": None,
    "Terra's Enmity": None,
    "Terra's Garrison": None,
    "Terra's Glory": None,
    "Terra's Healing": None,
    "Terra's Heed": None,
    "Terra's Majesty": None,
    "Terra's Might": None,
    "Terra's Might II": None,
    "Terra's Might III": None,
    "Terra's Mystery": None,
    "Terra's Primacy II": None,
    "Terra's Progression": None,
    "Terra's Tempering": None,
    "Terra's Third Spur": None,
    "Terra's Trium": None,
    "Terra's Tyranny": None,
    "Terra's Verity": None,
    "Terra's Verity II": None,
    "Terrae Excelsior": None,
    "Tetra's Essence": None,
    "Tetra's Nature": None,
    "The Butcher's Knife": None,
    "The Light in the Dark": None,
    "The Opening Draw": None,
    "The Phantom": None,
    "The Pulse": None,
    "Three-Sister Rule": None,
    "Thunder God's Authority": None,
    "Thunder God's Subjugation": None,
    "Thunder of the Sunrise": None,
    "Thunder's Aegis": None,
    "Thunder's Celere": None,
    "Thunder's Clarity": None,
    "Thunder's Dual-Edge": None,
    "Thunder's Enmity": None,
    "Thunder's Fandango": None,
    "Thunder's Garrison": None,
    "Thunder's Grace": None,
    "Thunder's Healing": None,
    "Thunder's Majesty": None,
    "Thunder's Might": None,
    "Thunder's Primacy": None,
    "Thunder's Progression": None,
    "Thunder's Restraint": None,
    "Thunder's Roar": None,
    "Thunder's Sentence": None,
    "Thunder's Stamina": None,
    "Thunder's Tempering": None,
    "Thunder's Trium": None,
    "Thunder's Verity": None,
    "Thunderswift Bladework": None,
    "Tidings of the New World": None,
    "Titan's Aegis": None,
    "Tranquility's Exertion": None,
    "Tranquility's Fortitude": None,
    "Tranquility's Pact": None,
    "Tranquility's Persistence": None,
    "Tranquility's Quenching": None,
    "Tranquility's Quintessence": None,
    "Tranquility's Spectacle": None,
    "Transcendent Cuteness": None,
    "Transience of Life": None,
    "Transmutation's Might": None,
    "Treasure Trick": None,
    "Trick or Treat": None,
    "Trick or Trick": None,
    "Trickster": None,
    "Triple Talon Hellion": None,
    "True Adjudicator's Supremacy": None,
    "True Dreadflame's Supremacy": None,
    "True Enchantment": None,
    "True Glacial Supremacy": None,
    "True Horseman's Supremacy": None,
    "True Phantom's Supremacy": None,
    "True Solaris's Supremacy": None,
    "Trump Card": None,
    "Trust in Me": None,
    "Tsunami's Aegis": None,
    "Tsunami's Celere": None,
    "Tsunami's Dual-Edge": None,
    "Tsunami's Enmity": None,
    "Tsunami's Essence": None,
    "Tsunami's Fandango": None,
    "Tsunami's Garrison": None,
    "Tsunami's Grace": None,
    "Tsunami's Haunt": None,
    "Tsunami's Healing": None,
    "Tsunami's Majesty": None,
    "Tsunami's Might": None,
    "Tsunami's Mystery": None,
    "Tsunami's Primacy": None,
    "Tsunami's Progression": None,
    "Tsunami's Restraint": None,
    "Tsunami's Sentence": None,
    "Tsunami's Stamina": None,
    "Tsunami's Trium": None,
    "Tsunami's Verity": None,
    "Tube Feet": None,
    "Tuna Toss": None,
    "Turbine's Might": None,
    "Twilight": None,
    "Two-Sword Tech": None,
    "Uncrossable Paradise": None,
    "Undefeated Hero": None,
    "Undersky's Hatebonds": None,
    "Undersky's Whispers": None,
    "Unidentified Forbidden Oomph": None,
    "Unrelenting Might": None,
    "Up in Arms": None,
    "Uriel's Blessing II": None,
    "Uriel's Blessing III": None,
    "V-Skill": None,
    "Venerator's Apex": None,
    "Venerator's Nature": None,
    "Ventosus's Aegis": None,
    "Ventosus's Bloodshed": None,
    "Ventosus's Demolishment": None,
    "Ventosus's Dual-Edge": None,
    "Ventosus's Enmity": None,
    "Ventosus's First Dash": None,
    "Ventosus's Garrison": None,
    "Ventosus's Glory": None,
    "Ventosus's Healing": None,
    "Ventosus's Heed": None,
    "Ventosus's Majesty": None,
    "Ventosus's Might": None,
    "Ventosus's Might II": None,
    "Ventosus's Might III": None,
    "Ventosus's Mystery": None,
    "Ventosus's Progression": None,
    "Ventosus's Stamina II": None,
    "Ventosus's Trium": None,
    "Ventosus's Tyranny": None,
    "Ventosus's Verity": None,
    "Ventosus's Verity II": None,
    "Verdant Sovereign": None,
    "Verglas Sovereign": None,
    "Vermillion Covenant": None,
    "Vertical Maneuvering Assault": None,
    "Vessel Phantasmic": None,
    "Vessel's Desolation": None,
    "Victorious Covenant": None,
    "Vigilante's Essence": None,
    "Vigilante's Nature": None,
    "Virtue's Champion": None,
    "Virtuoso's Essence": None,
    "Virtuoso's Nature": None,
    "Vision of the Future": None,
    "Visitor in the Night": None,
    "Vita Ignis": None,
    "Vita Imber": None,
    "Voidbroken Wing": None,
    "Voidcast Arrow": None,
    "Voidfeigned Crag": None,
    "Voidforged Lance": None,
    "Voidsung Grasp": None,
    "Volcanic Blade": None,
    "Vouge Hymn II": None,
    "Wamdus's Flood": None,
    "Wanderer's Essence": None,
    "Wanderer's Nature": None,
    "War God's Swing II": None,
    "War-Beast Bond": None,
    "Warlord's Lance": None,
    "Warrior Monk's Apex": None,
    "Warrior Monk's Nature": None,
    "Warrior's Assault": None,
    "Warrioress's Might": None,
    "Warspirit's Sword Dance": None,
    "Water's Aegis": None,
    "Water's Celere": None,
    "Water's Clarity": None,
    "Water's Dual-Edge": None,
    "Water's Enmity": None,
    "Water's Garrison": None,
    "Water's Grace": None,
    "Water's Healing": None,
    "Water's Majesty": None,
    "Water's Might": None,
    "Water's Mystery": None,
    "Water's Sentence": None,
    "Water's Stamina": None,
    "Water's Trium": None,
    "Water's Verity": None,
    "Weather Controller": None,
    "Weaver Stance": None,
    "Westerly Crescendo": None,
    "Westerly Rhapsody": None,
    "What Happens 2x, Happens 3x": None,
    "Whirlwind's Aegis": None,
    "Whirlwind's Betrayal": None,
    "Whirlwind's Celere": None,
    "Whirlwind's Clarity": None,
    "Whirlwind's Dual-Edge": None,
    "Whirlwind's Enmity": None,
    "Whirlwind's Essence": None,
    "Whirlwind's Fandango": None,
    "Whirlwind's Garrison": None,
    "Whirlwind's Grace": None,
    "Whirlwind's Haunt": None,
    "Whirlwind's Healing": None,
    "Whirlwind's Majesty": None,
    "Whirlwind's Might": None,
    "Whirlwind's Mystery": None,
    "Whirlwind's Primacy": None,
    "Whirlwind's Progression": None,
    "Whirlwind's Restraint": None,
    "Whirlwind's Stamina": None,
    "Whirlwind's Trium": None,
    "Whirlwind's Verity": None,
    "Whispers of Death": None,
    "White Covenant": None,
    "Wicked Fangs": None,
    "Wicked Sick Might": None,
    "Wild Wanderer": None,
    "Wilnas's Firestorm": None,
    "Wind's Aegis": None,
    "Wind's Celere": None,
    "Wind's Clarity": None,
    "Wind's Enmity": None,
    "Wind's Fandango": None,
    "Wind's Garrison": None,
    "Wind's Healing": None,
    "Wind's Majesty": None,
    "Wind's Might": None,
    "Wind's Mystery": None,
    "Wind's Restraint": None,
    "Wind's Sentence": None,
    "Wind's Trium": None,
    "Wind's Verity": None,
    "Wings of Divinity": None,
    "With This, I'm Invincible!": None,
    "Yes, My Lord!": None,
    "Zenith Art": None,
    "Zenith Strike": None,
    "Zero to Hero": None,
    "Zion's Aegis": None,
    "Zion's Celere II": None,
    "Zion's Crux": None,
    "Zion's Dual-Edge": None,
    "Zion's Enmity": None,
    "Zion's Fandango": None,
    "Zion's Garrison": None,
    "Zion's Glory": None,
    "Zion's Healing": None,
    "Zion's Heed": None,
    "Zion's Majesty": None,
    "Zion's Might": None,
    "Zion's Might II": None,
    "Zion's Might III": None,
    "Zion's Mystery": None,
    "Zion's Progression": None,
    "Zion's Stamina": None,
    "Zion's Tempering": None,
    "Zion's Trium": None,
    "Zion's Tyranny": None,
    "Zion's Tyranny II": None,
}
